apiVersion: v1
kind: Service
metadata:
  name: vaultly-control-api
  namespace: vaultly-control
  labels:
    app: vaultly-control-api
spec:
  type: ClusterIP
  selector:
    app: vaultly-control-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
