apiVersion: v1
kind: Service
metadata:
  name: vaultly-control-web
  namespace: vaultly-control
  labels:
    app: vaultly-control-web
spec:
  type: ClusterIP
  selector:
    app: vaultly-control-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
